server:
  port: 7007

spring:
  config:
    import: optional:file:.env  # ✅ .env 파일을 불러오는 설정 추가

  security:
    jwt:
      secret: ${JWT_SECRET}  # ✅ JWT 서명용 비밀 키 추가
      expiration: ${JWT_EXPIRATION}  # ✅ JWT 만료 시간 (1시간, 1000 * 60 * 60)

    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: ${GOOGLE_REDIRECT_URI}

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${NAVER_REDIRECT_URI}
            scope:
              - name
              - email
            client-name: Naver

          kakao:
            client-id: ${KAKAO_CLIENT_ID}  # ✅ 카카오 REST API 키
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id  # ✅ 카카오는 기본적으로 "id" 값 제공

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://192.168.0.77:3306/trip_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: root
      password: abcd1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 20000
      validation-timeout: 3000
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: HikariCP

logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}:%line)-%msg%n}"
  level:
    org.springframework.security: TRACE

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
