server:
  port: 7007

spring:
  output:
    ansi:
      enabled: always # 콘솔 로그 색상 활성화

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/trip_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: root
      password: abcd1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 20000
      validation-timeout: 3000
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: HikariCP

logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}:%line)-%msg%n}"
  level:
    org.springframework.security: TRACE

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

