server:
  port: 7007

spring:
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/resources/, classpath:/META-INF/resources/
      cache:
        period: 3600  # 캐시 지속 시간 (초 단위)

  config:
    import: optional:file:.env  # ✅ .env 파일을 불러오는 설정 추가 (일단 인식이 잘 안되어 대기)

  security:
    jwt:
      secret: "8066e49cb4ddf852d9dcb187d3c4eef52f499f96a300312e6645cfb4e9d5924e" # git bash -> openssl rand -base64 32
      expiration: 604800000 #3600000 # 만료시간
      #refresh-expiration: 360000  # 리프레시 토큰 30초 만료

    oauth2:
      client:
        registration:
          google:
            client-id: 1079080191923-bfsmh4mludaa0psak7odfkgj8ca6orv5.apps.googleusercontent.com # 구글 client-id
            client-secret: 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 # 구글 secret
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"  # ✅ Google Console과 동일하게 유지

          naver:
            client-id: vTYo4QlMYeUOXDIq9438
            client-secret: E9wUXYgk7e
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope:
              - name
              - email
            client-name: naver

          kakao:
            client-id: ${KAKAO_CLIENT_ID}  # ✅ 카카오 REST API 키
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id  # ✅ 카카오는 기본적으로 "id" 값 제공
  
  mail:
    gmail:
      host: smtp.gmail.com
      port: 587
      username: gmlqja55@gmail.com
      password: "ovbh fivx sylu hibb" # SMTP 앱 비밀번호 사용
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true

    naver:
      host: smtp.naver.com
      port: 587
      username: ksje1102@naver.com
      password: "444F1JBHVSMH"  # ❗ SMTP 앱 비밀번호 사용
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://203.234.214.71:3306/trip_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: root
      password: abcd1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 20000
      validation-timeout: 3000
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: HikariCP

logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}:%line)-%msg%n}"
  level:
    org.springframework.security: TRACE

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
