server:
  port: 7007

spring:
  output:
    ansi:
      enabled: always # 콘솔 로그 색상 활성화

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/trip_db?serverTimezone=Asia/Seoul
      username: root
      password: abcd1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 20000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}:%line)-%msg%n}"
  level:
    org.springframework.security: TRACE

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
