server:
  port: 7007 # 서버 포트 변경

spring:
  output:
    ansi:
      enabled: always # 콘솔 로그 색상 활성화

  thymeleaf:
    prefix: classpath:/templates/ # Thymeleaf 템플릿 경로 설정
    suffix: .html # HTML 파일 확장자 설정
    cache: false # 개발 중 변경 사항 즉시 반영

logging:
  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}:%line)-%msg%n}"
  level:
    org.springframework.security: "${SPRING_SECURITY_LOG_LEVEL:TRACE}" # Spring Security 로그 레벨 (TRACE)